server:
  port: 8080
spring:
  #数据库连接配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/doudiz?characterEncoding=utf-8&useSSL=true
    username: landlord
    password: a789456123
mybatis:
  #mapper配置文件
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.clx.doudiz.domain.mapper
  #开启驼峰命名
  configuration:
    map-underscore-to-camel-case: true