server:
  port: 8081
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/doudiz?characterEncoding=utf-8&useSSL=true&&serverTimezone=Asia/Shanghai
    username: landlord
    password: a789456123
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.clx.doudiz.domain.mapper
  configuration:
    map-underscore-to-camel-case: true